"""enable pgvector

Revision ID: 0001
Revises:
Create Date: 2026-08-06

Hand-written, not autogenerated.

The extension is created here and ONLY here. The tempting alternative,
/docker-entrypoint-initdb.d/, runs only when the data directory is empty — so adding
pgvector to an existing volume silently never fires, and you get a mystery
`type "vector" does not exist` on a machine that worked yesterday. The migration is
the only place that also runs in CI, on a teammate's machine, and on managed Postgres.

Note `vector.control` has no `trusted = true`, so this requires superuser. Locally the
POSTGRES_USER created by the entrypoint is one; a managed provider will need a role
with rds_superuser or equivalent.
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # One statement per op.execute(): psycopg rejects multi-statement prepared
    # statements, and a combined string would fail only on some drivers.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")


def downgrade() -> None:
    op.execute("DROP EXTENSION IF EXISTS vector")
