"""initial schema

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-06 14:59:03.498741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # noqa: F401 — generated VECTOR/HALFVEC columns need it
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('ats_type', sa.Text(), nullable=False),
    sa.Column('ats_slug', sa.Text(), nullable=False),
    sa.Column('last_seen_ok', sa.DateTime(timezone=True), nullable=True),
    sa.Column('jobs_last_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("ats_type IN ('greenhouse', 'lever', 'ashby', 'workable', 'smartrecruiters', 'recruitee', 'other')", name=op.f('ck_companies_ats_type')),
    sa.CheckConstraint("status IN ('active', 'retired', 'error')", name=op.f('ck_companies_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('ats_type', 'ats_slug', name=op.f('uq_companies_ats_type_ats_slug'))
    )
    op.create_index('ix_companies_jobs_last_run', 'companies', ['jobs_last_run'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_table('jobs',
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('company', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('remote', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('ats_type', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("ats_type IS NULL OR ats_type IN ('greenhouse', 'lever', 'ashby', 'workable', 'smartrecruiters', 'recruitee', 'other')", name=op.f('ck_jobs_ats_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('source', 'external_id', name=op.f('uq_jobs_source_external_id'))
    )
    op.create_table('users',
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('auth_id', sa.Text(), nullable=False),
    sa.Column('plan', sa.Text(), server_default='free', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("plan IN ('free', 'pro')", name=op.f('ck_users_plan')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('auth_id', name=op.f('uq_users_auth_id')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index('ix_events_user_id_created_at', 'events', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('job_embeddings',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.halfvec.HALFVEC(dim=1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_embeddings_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'model', name=op.f('pk_job_embeddings'))
    )
    op.create_table('matches',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('reasons_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.Text(), server_default='discovered', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("label IS NULL OR label IN ('good_fit', 'fair', 'reach')", name=op.f('ck_matches_label')),
    sa.CheckConstraint("status IN ('discovered', 'tailored', 'queued', 'approved', 'applied', 'skipped')", name=op.f('ck_matches_status')),
    sa.CheckConstraint('score IS NULL OR score BETWEEN 0 AND 100', name=op.f('ck_matches_score_range')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_matches_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_matches_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches')),
    sa.UniqueConstraint('user_id', 'job_id', name=op.f('uq_matches_user_id_job_id'))
    )
    op.create_index('ix_matches_status_user_id', 'matches', ['status', 'user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('master_resume', sa.Text(), nullable=True),
    sa.Column('parsed_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('prefs_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('work_auth', sa.Text(), nullable=True),
    sa.Column('locations', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('seniority', sa.Text(), nullable=True),
    sa.Column('salary_floor', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("seniority IS NULL OR seniority IN ('intern', 'junior', 'mid', 'senior', 'staff', 'principal', 'lead', 'director')", name=op.f('ck_profiles_seniority')),
    sa.CheckConstraint("work_auth IS NULL OR work_auth IN ('citizen', 'permanent_resident', 'visa_holder', 'needs_sponsorship')", name=op.f('ck_profiles_work_auth')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles'))
    )
    op.create_index('ix_profiles_locations', 'profiles', ['locations'], unique=False, postgresql_using='gin')
    op.create_index('ix_profiles_user_id', 'profiles', ['user_id'], unique=False)
    op.create_table('applications',
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmation', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method IN ('agent', 'extension', 'manual')", name=op.f('ck_applications_method')),
    sa.CheckConstraint("status IN ('pending', 'submitted', 'failed')", name=op.f('ck_applications_status')),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_applications_match_id_matches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('match_id', 'method', name=op.f('uq_applications_match_id_method'))
    )
    op.create_table('approvals',
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('telegram', 'dashboard')", name=op.f('ck_approvals_channel')),
    sa.CheckConstraint("decision IS NULL OR decision IN ('approved', 'skipped')", name=op.f('ck_approvals_decision')),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_approvals_match_id_matches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals'))
    )
    op.create_index('uq_approvals_pending', 'approvals', ['match_id', 'channel'], unique=True, postgresql_where=sa.text('decided_at IS NULL'))
    op.create_table('documents',
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('storage_url', sa.Text(), nullable=False),
    sa.Column('gdrive_url', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('resume', 'cover_letter')", name=op.f('ck_documents_type')),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_documents_match_id_matches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('match_id', 'type', 'version', name=op.f('uq_documents_match_id_type_version'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.drop_index('uq_approvals_pending', table_name='approvals', postgresql_where=sa.text('decided_at IS NULL'))
    op.drop_table('approvals')
    op.drop_table('applications')
    op.drop_index('ix_profiles_user_id', table_name='profiles')
    op.drop_index('ix_profiles_locations', table_name='profiles', postgresql_using='gin')
    op.drop_table('profiles')
    op.drop_index('ix_matches_status_user_id', table_name='matches')
    op.drop_table('matches')
    op.drop_table('job_embeddings')
    op.drop_index('ix_events_user_id_created_at', table_name='events')
    op.drop_table('events')
    op.drop_table('users')
    op.drop_table('jobs')
    op.drop_index('ix_companies_jobs_last_run', table_name='companies', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('companies')
    # ### end Alembic commands ###
