"""lossless job location and one profile per user

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-06 15:46:17.646391

Two corrections made while `jobs` and `profiles` are still empty.

1. `jobs.remote BOOLEAN` -> `jobs.remote_mode TEXT` + `jobs.locations TEXT[]`.
   Verified against live responses from all six ATS providers: Recruitee returns three
   non-exclusive booleans (remote/hybrid/on_site), Ashby has `isRemote` plus a separate
   `workplaceType`, SmartRecruiters has `remote` plus `hybrid`. A boolean silently
   flattens every hybrid role, and a scalar `location` drops every posting with
   `secondaryLocations[]` / `locations[]`.

   This drops a column, which §6.2 would normally forbid in favour of add-plus-backfill.
   It is safe *only* because the table has no rows yet. Once M1 ingestion starts, the
   same change costs a new column and a backfill — which is precisely why it is being
   made now rather than then.

2. `profiles.user_id` gains UNIQUE. The rest of the schema already assumed one profile
   per user: `matches` is unique on (user_id, job_id) and carries no profile_id, so two
   profiles would give a job one score with nowhere to record the second.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # noqa: F401 — generated VECTOR/HALFVEC columns need it
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('locations', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False))
    op.add_column('jobs', sa.Column('remote_mode', sa.Text(), nullable=True))
    op.create_index('ix_jobs_locations', 'jobs', ['locations'], unique=False, postgresql_using='gin')
    op.create_check_constraint(op.f('ck_jobs_remote_mode'), 'jobs', "remote_mode IS NULL OR remote_mode IN ('remote', 'hybrid', 'onsite')")
    op.drop_column('jobs', 'remote')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.create_unique_constraint(op.f('uq_profiles_user_id'), 'profiles', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_profiles_user_id'), 'profiles', type_='unique')
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=False)
    op.add_column('jobs', sa.Column('remote', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('ck_jobs_remote_mode'), 'jobs', type_='check')
    op.drop_index('ix_jobs_locations', table_name='jobs', postgresql_using='gin')
    op.drop_column('jobs', 'remote_mode')
    op.drop_column('jobs', 'locations')
    # ### end Alembic commands ###
