"""add job company_id and closed_at, company failure counter

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-06 16:40:19.293362

The three columns M1's gate needs and the schema does not have yet.

1. `jobs.company_id` -> `companies.id`. The registry resolves it at ingest time. Scoping
   is the point: "close every posting this board stopped returning" needs a way to say
   *this board*, and matching on the raw `company` text would close another company's
   rows the moment two boards spell a name differently. Nullable because M2's aggregator
   rows name employers we may hold no registry row for. ON DELETE SET NULL, not CASCADE:
   retiring a dead board must not delete the jobs it produced.

2. `jobs.closed_at`. NULL = still listed. A timestamp rather than a status enum — it
   records *when* a posting vanished, which a boolean throws away, and it needs no CHECK
   constraint to drop and re-add every time the vocabulary changes.

   The partial index alongside it is the access path for both the close statement and
   M4's "score only open jobs". Partial so it stays small as closed rows accumulate,
   which they will: a board's history grows without bound while its open set does not.

3. `companies.consecutive_failures`. §4.3 calls for auto-retiring slugs that 404 for N
   runs, and there was nowhere to count. Reset to zero on any successful fetch, so only
   *consecutive* failures accumulate and one transient 503 never retires a live board.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # noqa: F401 — generated VECTOR/HALFVEC columns need it


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('consecutive_failures', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('jobs', sa.Column('company_id', sa.Uuid(), nullable=True))
    op.add_column('jobs', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_jobs_company_id_open', 'jobs', ['company_id'], unique=False, postgresql_where=sa.text('closed_at IS NULL'))
    op.create_foreign_key(op.f('fk_jobs_company_id_companies'), 'jobs', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_jobs_company_id_companies'), 'jobs', type_='foreignkey')
    op.drop_index('ix_jobs_company_id_open', table_name='jobs', postgresql_where=sa.text('closed_at IS NULL'))
    op.drop_column('jobs', 'closed_at')
    op.drop_column('jobs', 'company_id')
    op.drop_column('companies', 'consecutive_failures')
    # ### end Alembic commands ###
