"""job dedupe key and canonical id

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-07 11:48:54.416372

M2's gate: an overlapping company collapses to one row and the survivor keeps the ATS
apply URL. Two columns carry it.

1. `jobs.dedupe_key` — §4.2's normalized `company|title|location`. TEXT written by
   Python rather than GENERATED ALWAYS AS: the normalizer strips legal suffixes and
   requisition ids by token, which as a generated column would mean maintaining the
   same rules a second time as an IMMUTABLE SQL function, testable only through a
   container. It would also make changing one rule a full table rewrite under ACCESS
   EXCLUSIVE, where here it is `UPDATE jobs SET dedupe_key = NULL WHERE closed_at IS
   NULL` and the next pass reconverges.

   NULL means either "not keyed yet" (a fresh insert) or "un-keyable" (blank company or
   title). Both are the safe reading: a NULL-keyed row is never merged with anything.

   The partial index is the steady-state access path. The dedupe pass opens by keying
   every open row that has none, and after the first backfill that has to be an empty
   index scan rather than a scan of every open row, on every tick, forever.

2. `jobs.canonical_id` -> `jobs.id`. NULL = this row is the survivor. That polarity
   rather than self-pointing, for two reasons: `canonical_id IS NULL` is an indexable
   predicate M4 can use directly, and every row that predates this migration is
   already correctly marked without a data step.

   ON DELETE SET NULL, not CASCADE. Deleting a winner must promote its duplicates back
   to survivors, never delete real postings.

   Losers are marked, never deleted. `upsert` conflicts on (source, external_id); a
   deleted row has no conflict target, so the source's next pass re-inserts it and the
   run rewrites rows forever — §6.3's "writes only diffs" quietly gone.

   The CHECK makes "NULL = survivor" a database fact. A row pointing at itself would be
   excluded from `canonical_id IS NULL` and silently vanish from the deduped pool.

No data step here. The dedupe pass backfills itself, because adding the key to
`_MUTABLE` could never reach a pre-existing row: the upsert's diff predicate blocks the
write for every row whose payload has not changed, which is all of them.
"""

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401 — generated VECTOR/HALFVEC columns need it
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str | Sequence[str] | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("jobs", sa.Column("dedupe_key", sa.Text(), nullable=True))
    op.add_column("jobs", sa.Column("canonical_id", sa.Uuid(), nullable=True))
    op.create_index(
        "ix_jobs_dedupe_key_open",
        "jobs",
        ["dedupe_key"],
        unique=False,
        postgresql_where=sa.text("closed_at IS NULL"),
    )
    op.create_foreign_key(
        op.f("fk_jobs_canonical_id_jobs"),
        "jobs",
        "jobs",
        ["canonical_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_check_constraint(
        op.f("ck_jobs_canonical_id_not_self"), "jobs", "canonical_id IS NULL OR canonical_id <> id"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_jobs_canonical_id_not_self"), "jobs", type_="check")
    op.drop_constraint(op.f("fk_jobs_canonical_id_jobs"), "jobs", type_="foreignkey")
    op.drop_index(
        "ix_jobs_dedupe_key_open", table_name="jobs", postgresql_where=sa.text("closed_at IS NULL")
    )
    op.drop_column("jobs", "canonical_id")
    op.drop_column("jobs", "dedupe_key")
    # ### end Alembic commands ###
