"""evidence vault and resume url

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-07 15:45:00.000000

M3's gate clause: "Evidence vault populated for one test user." The vault is two parts —
`profiles.master_resume`, which already existed, and this table.

1. `evidence` — one row per atomic claim about the user, each with `text` that appears
   **verbatim in that profile's master_resume**. `vault.py` verifies that on write; the
   database only stores the result.

   A table rather than a JSONB key on `profiles`, for a lifecycle reason rather than a
   normalisation one. `parsed_json` is *derived*: a re-parse throws it away and rebuilds
   it. The vault is not — it also holds `origin='user'` claims a person added by hand,
   and those have to survive a re-upload. Same row, two lifetimes, so two homes.

   The unique constraint on (profile_id, kind, text) is what makes a re-parse
   idempotent: the same résumé produces the same claims and the database refuses the
   second copy, rather than the code doing check-then-act.

   `origin` decides what a re-parse may delete. Without it, rebuilding the parsed set
   either wipes a user's hand-added facts or leaves stale ones behind forever.

   CASCADE from `profiles`, because a claim means nothing detached from the résumé it
   was verified against — unlike `jobs.company_id`, where history outlives the board.

2. `profiles.resume_url` — the object-storage key for the raw upload. A key, not a full
   URL: bucket and endpoint are deployment config, and baking them into rows makes
   moving buckets a data migration. The extension stays on the key because the extractor
   needs the format hint.

No data step. Existing profiles have no résumé on file and no claims, which is already
the correct state for both columns.
"""

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401 — generated VECTOR/HALFVEC columns need it
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: str | Sequence[str] | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evidence",
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("origin", sa.Text(), server_default="user", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('skill', 'bullet', 'title', 'credential')", name=op.f("ck_evidence_kind")
        ),
        sa.CheckConstraint("origin IN ('parsed', 'user')", name=op.f("ck_evidence_origin")),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_evidence_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
        sa.UniqueConstraint(
            "profile_id", "kind", "text", name=op.f("uq_evidence_profile_id_kind_text")
        ),
    )
    op.create_index("ix_evidence_profile_id_kind", "evidence", ["profile_id", "kind"], unique=False)
    op.add_column("profiles", sa.Column("resume_url", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profiles", "resume_url")
    op.drop_index("ix_evidence_profile_id_kind", table_name="evidence")
    op.drop_table("evidence")
    # ### end Alembic commands ###
