"""Column mixins shared by every model."""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, Uuid, func, text
from sqlalchemy.orm import Mapped, mapped_column


class UUIDv7PK:
    """Primary key generated by Postgres 18's native `uuidv7()`.

    v7 keeps bigserial's index locality without exposing an enumerable counter — which
    matters because the M9 browser extension talks to this API over the internet.

    `server_default`, not a Python default: the database stays authoritative, so bulk
    COPY and raw-SQL insert paths get IDs too.
    """

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, server_default=text("uuidv7()"))


class CreatedAt:
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class Timestamps(CreatedAt):
    """`now()` is transaction_timestamp() — constant across every row one worker
    writes in a transaction, which is what we want for consistency.

    `onupdate` is Python-side and so only fires on ORM writes. Every write at M0 is
    ORM. Add a DB trigger when a raw-SQL path starts lying about `updated_at`.
    """

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )
